import{a as $,i as l,S as C}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const B="https://pixabay.com/api/",E="49758649-878ce1f589e8b6bdc26fd775c";async function h(t,r=1){const s=await $.get(`${B}`,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}});return s.data.hits.length||l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),s.data}const L=document.querySelector(".gallery"),b=document.querySelector(".loader"),S=document.querySelector(".btn-load-more");var P=new C(".gallery-link",{captionsData:"alt",captionDelay:250});function q(t){const r=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:u,comments:x,downloads:_})=>`<li class="gallery-item">
    <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${e}"
    />
   </a>
    <ul class="info">
      <li class="info-item">
        <h3 class="info-title">Likes</h3>
        <p class="info-text">${o}</p>
      </li>
      <li class="info-item"><h3 class="info-title">Views</h3> <p class="info-text">${u}</p></li>
      <li class="info-item"><h3 class="info-title">Comments</h3> <p class="info-text">${x}</p></li>
      <li class="info-item"><h3 class="info-title">Downloads</h3> <p class="info-text">${_}</p></li>
    </ul>
    </li>`).join("");L.insertAdjacentHTML("beforeend",r),P.refresh()}function T(){L.innerHTML=""}function v(){b.classList.remove("hiden")}function f(){b.classList.add("hiden")}function w(){S.classList.remove("hiden")}function d(){S.classList.add("hiden")}const M=document.querySelector(".form"),H=document.querySelector(".btn-load-more");M.addEventListener("submit",O);H.addEventListener("click",k);let c=1,g="",m=0;const i={q:"",colors:"",category:"",per_page:15,page:1};let n=15;async function O(t){t.preventDefault(),v();const r=t.currentTarget.elements["search-text"].value.trim(),s=t.currentTarget.elements.select_colors.value,a=t.currentTarget.elements.select_category.value;if(n=t.currentTarget.elements.select_quantity.value,n===""&&(n=15),g=r,c=1,i.q=g,i.colors=s,i.page=c,i.category=a,i.per_page=n,r===""){l.info({title:"Caution",message:"You forgot important data",position:"topLeft"}),f();return}try{const e=await h(i);m=e.totalHits,T(),q(e.hits),c*n<m?w():(l.info({title:"Caution",message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}),d())}catch(e){l.error({title:"Error",message:`${e.message}`}),d()}finally{f()}}async function k(){c++,i.page=c,v(),d();try{const t=await h(i);q(t.hits);const r=c*n;console.log(r),r<m?w():l.info({title:"Caution",message:"We're sorry, but you've reached the end of search results.",position:"topLeft"});const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch(t){l.error({title:"Error",message:`${t.message}`}),d()}finally{f()}}const p=document.querySelector("#toggleFilters"),y=document.querySelector(".filters_container");p.addEventListener("click",()=>{const t=y.style.display==="block";y.style.display=t?"none":"block",p.textContent=t?"🔽 Show Filters":"🔼 Hide Filters"});
//# sourceMappingURL=index.js.map
